### ISSUE TITLE
Allow links to open in new tab/window

### ISSUE THREAD

**Issue by mgoodhand** [plotly/dash-html-components#23] opened 2017-10-10 11:07 UTC
Like many people, I often open links in a new tab (Ctrl-click).

`dcc.Link` appears not to support this.

[React Router](https://github.com/ReactTraining/react-router/issues/2188) appears to support this via `target="_blank"`, but the target attribute is not allowed on `dcc.Link`.

**Comment by rmarren1** [comment] 2018-03-07 19:25
html.A has a `target` attribute you can set: https://github.com/plotly/dash-html-components/blob/c507b4f6eddeda252849997d6b16ed90830d69b2/src/components/A.react.js#L91

**Comment by chriddyp** [comment] 2018-03-07 19:38
duplicate of https://github.com/plotly/dash-core-components/issues/129

**Comment by exbald** [comment] 2018-07-19 18:45
`html.Div([html.A('Link', href='https://dash.plot.ly', target='_blank')]`
this will open link in new tab

**Comment by chriddyp** [comment] 2018-07-19 18:52
This was fixed in the `dcc.Link` component in https://github.com/plotly/dash-core-components/pull/215

**Closed by chriddyp** 2018-07-19 18:52 UTC

**Comment by yogesh-ezest** [comment] 2020-03-11 09:14
> `html.Div([html.A('Link', href='https://dash.plot.ly', target='_blank')]`
> this will open link in new tab
@chriddyp Yes. How do I do this in dashtable cell where data is rendered from dataframe. I am able to do this using markdown in dashtable cell, but the link is opened in same tab and I am loosing my previous result. 
Could you please suggest me how to open the link in new tab/window using markdown?
